
version: 2
updates:
  # Configurazione per Gradle (dipendenze Android/Kotlin)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Rome"
    assignees:
      - "Sdrogo" # OK
    commit-message:
      prefix: "deps"
    groups:
      androidx-compose:
        patterns:
          - "androidx.compose*"
      androidx-lifecycle:
        patterns:
          - "androidx.lifecycle*"
      firebase:
        patterns:
          - "com.google.firebase*"

  # Configurazione per GitHub Actions (workflow del CI/CD)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "Sdrogo" # FIXED
    commit-message:
      prefix: "ci"
