name: Android CI & Release

on:
  push:
    branches:
      - "master"
      - "feature/*"
      - "bugfix/*"
  pull_request:
    branches:
      - "master"
      - "feature/*"
      - "bugfix/*"

jobs:
  # JOB 1: ANALISI DEL CODICE (SENZA FIRMA)
  # Questo job viene eseguito su ogni push e PR. Fa un build di debug sufficiente per l'analisi.
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Permesso per CodeQL
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Per l'analisi non servono né google-services.json né le chiavi di firma.
      # Questo rende il processo più veloce e sicuro.
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java-kotlin

      # Eseguiamo un build di debug. È sufficiente per l'analisi di CodeQL.
      - name: Build Debug for Analysis
        run: ./gradlew assembleDebug

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  # JOB 2: CREAZIONE DELL'APK FIRMATO (SOLO SU MASTER)
  # Questo job viene eseguito solo dopo un merge su master. È isolato e dedicato alla release.
  build-and-release:
    # Esegui questo job solo dopo che l'analisi è passata
    needs: analyze
    # Esegui solo su push (merge) verso il branch master
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
        contents: write # Permesso per caricare l'artefatto

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Create google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > app/google-services.json

      - name: Decode Keystore
        run: echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Questo è il build di release vero e proprio
      - name: Build Signed Release APK
        run: ./gradlew clean assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: V5Rules-Release-APK
          path: app/build/outputs/apk/release/app-release.apk
